In [ ]:
# NumPy is a Python library used for working with arrays.

# It also has functions for working in domain of linear algebra, fourier transform, and matrices.

In [1]:
import numpy

arr = numpy.array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


In [2]:
# NumPy as np

import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


In [3]:
# The version string is stored under __version__ attribute.

import numpy as np

print(np.__version__)

1.19.1


In [4]:
# The array object in NumPy is called ndarray.

# We can create a NumPy ndarray object by using the array() function.

import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)

print(type(arr)) # type(): This built-in Python function tells us the type of the object passed to
                   # it. Like in above code it shows that arr is numpy.ndarray type.

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# To create an ndarray, we can pass a list, tuple or any array-like object into the array() method
   # and it will be converted into an ndarray:

In [5]:
# Use a tuple to create a NumPy array:

import numpy as np

arr = np.array((1,2,3,4,5))

print(arr)

[1 2 3 4 5]


In [ ]:
# A dimension in arrays is one level of array depth (nested arrays).
# 0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [6]:
# Create a 0-D array with value 42

import numpy as np

arr = np.array(42)

print(arr)

42


In [7]:
# An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
# Create a 1-D array containing the values 1,2,3,4,5:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [8]:
# An array that has 1-D arrays as its elements is called a 2-D array.

# Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:

import numpy as np

arr = np.array([[1,2,3], [4,5,6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [11]:
# An array that has 2-D arrays (matrices) as its elements is called 3-D array.

# Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 
   # 4,5,6:
    
import numpy as np

arr = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [13]:
# NumPy Arrays provides the "ndim" attribute that returns an integer that tells us how many 
   # dimensions the array have.
    
# Check how many dimensions the arrays have:

import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [15]:
# When the array is created, you can define the number of dimensions by using the "ndmin" argument

# Create an array with 5 dimensions and verify that it has 5 dimensions:

import numpy as np

arr = np.array([1,2,3,4,5], ndmin = 5)

print(arr)
print('Number of dimensions :', arr.ndim)

[[[[[1 2 3 4 5]]]]]
Number of dimensions : 5


In [16]:
# NumPy Array Indexing

# Get the first element from the following array:

import numpy as np

arr = np.array([1,2,3,4,5])

print(arr[0])

1


In [17]:
# Get third and fourth elements from the following array and add them.

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [ ]:
# Access 2-D Arrays

# To access elements from 2-D arrays we can use comma separated integers representing the 
   # dimension and the index of the element.

In [18]:
# Access the 2nd element on 1st dim:

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st dim: ', arr[0, 1])

2nd element on 1st dim:  2
